# Generated by Django 5.0 on 2024-01-11 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="email",
        ),
    ]
