# Generated by Django 5.0 on 2024-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tel_number",
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
