# Generated by Django 5.0 on 2024-01-23 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_tel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tel_number",
            field=models.CharField(
                blank=True,
                max_length=65,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+[0-9]{1,3}\\.[0-9]{4,14}(?:x.+)?$",
                        message="Make sure your phone number is in accordance with the format: +CCC.NNNNNNNNNNxEEEE, where C is the 1–3 digit country code, N is up to 14 digits, and E is the (optional) extension",
                    )
                ],
            ),
        ),
    ]
