# Generated by Django 5.0 on 2024-01-23 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_tel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tel_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$",
                        message="Make sure your phone number consists of 10 digits",
                    )
                ],
            ),
        ),
    ]
