# Generated by Django 5.0 on 2024-01-12 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="sasha", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="bryl", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                default="+380989322157",
                max_length=65,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+[0-9]{1,3}\\.[0-9]{4,14}(?:x.+)?$",
                        message="Make sure your phone number is in accordance with the format:\n +CCC.NNNNNNNNNNxEEEE, where C is the 1–3 digit country code, N is up to 14 digits, and E is the (optional) extension",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
