# Generated by Django 5.0 on 2024-01-11 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
