# Generated by Django 5.0 on 2024-01-12 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_first_name_order_last_name_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                max_length=65,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+[0-9]{1,3}\\.[0-9]{4,14}(?:x.+)?$",
                        message="Make sure your phone number is in accordance with the format: +CCC.NNNNNNNNNNxEEEE, where C is the 1–3 digit country code, N is up to 14 digits, and E is the (optional) extension",
                    )
                ],
            ),
        ),
    ]
