# Generated by Django 5.0 on 2024-01-15 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_phone_number"),
        ("order", "0004_remove_order_products_alter_order_phone_number"),
    ]

    operations = []
