# Generated by Django 5.0 on 2024-01-23 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_merge_20240115_2222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$",
                        message="Make sure your phone number consists of 10 digits",
                    )
                ],
            ),
        ),
    ]
