# Generated by Django 5.0 on 2024-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_order_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chernihivska", "Чернігівська область"),
                    ("Cherkaska", "Черкаська область"),
                    ("Chernivetska", "Чернівецька область"),
                    ("Dnipropetrovska", "Дніпропетровська область"),
                    ("Donetska", "Донецька область"),
                    ("Ivano-Frankivska", "Івано-Франківська область"),
                    ("Kharkivska", "Харківська область"),
                    ("Khersonska", "Херсонська область"),
                    ("Khmelnytska", "Хмельницька область"),
                    ("Kirovohradska", "Кіровоградська область"),
                    ("Kyivska", "Київська область"),
                    ("Luhanska", "Луганська область"),
                    ("Lvivska", "Львівська область"),
                    ("Mykolaivska", "Миколаївська область"),
                    ("Odeska", "Одеська область"),
                    ("Poltavska", "Полтавська область"),
                    ("Rivnenska", "Рівненська область"),
                    ("Sumska", "Сумська область"),
                    ("Ternopilska", "Тернопілська область"),
                    ("Vinnytska", "Вінницька область"),
                    ("Volynska", "Волинська область"),
                    ("Zakarpatska", "Закарпатська область"),
                    ("Zaporizka", "Запорізька область"),
                    ("Zhytomirska", "Житомирська область"),
                    ("Crimea", "АР Крим"),
                ],
                max_length=65,
                null=True,
            ),
        ),
    ]
